; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 04 2017 15:17:46 GMT-0700 (MST)

; Lift Z relatively to current position
G91
G1 Z5 F6000

; Back to absolute positioning
G90

; Go to first bed probe point and home the Z axis
G1 X15 Y15 F6000
G30

; Uncomment the following lines to lift Z after probing
;G91
;G1 Z5 F100
;G90
