; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 04 2017 12:26:00 GMT-0700 (MST)

; Relative positioning
G91

; Lift Z
G1 Z5 F6000

; Course home X and Y
G1 X-215 Y-215 F1800 S1

; Move away from the endstops
G1 X5 Y5 F6000

; Fine home X and Y
G1 X-215 Y-215 F360 S1

; Absolute positioning
G90

; Go to first bed probe point and home Z
G1 X15 Y15 F6000
G30

; Uncomment the following line to lift the nozzle after probing
;G1 Z5 F100

